apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: movies
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: movies
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  build:
      env:
      - name: BP_JVM_VERSION
        value: "17.*"
  serviceClaims:
  - name: db
    ref:
      apiVersion: with.sql.tanzu.vmware.com/v1
      kind: MySQL
      name: mysql-movies
  source:
    git:
      url: https://github.com/ryanjbaxter/movies
      ref:
        branch: main